Files to register and to receive notifications
gotify/android-connector pull request #1
Opened 2020-06-21 19:43 UTC by gougeon-s

2020-06-23 17:21 UTC, jmattheis commented on GotifyServiceNotification.kt
> +open class GotifyServiceNotification : Service() {
Currently, this code is more example code than lib code, because it isn't really extensible. Users of the android-connector lib should be able to pass a callback to our gHandler and then be able to register the handler themselves.

the Callback could look like this (not finished)
```
    interface Handler {
        void onMessage(Message message);
        void onRegister(String token, String url);
    }
```
The connector lib should only provide a more user-friendly interface.

See also https://developer.android.com/studio/projects/android-library

2020-10-22 10:54 UTC, p1gp1g commented
The two last commits made it like a lib. 

```
        override fun handleMessage(msg: Message) {
            when (msg.what) {
                TYPE_CHANGED_URL -> if (checkGotifyId(msg.sendingUid)) newUrl(msg)
                TYPE_MESSAGE -> if (checkGotifyId(msg.sendingUid)) showNotification(msg)
                else -> super.handleMessage(msg)
            }
        }
```
If you want to, we can rename newUrl and showNotification to onNewUrl and onMessage (or something like that)

2020-10-29 20:21 UTC, jmattheis commented
Hi! I'm currently a little busy and I want to take the time to properly understand this code before reviewing / merging it. I'll try to do it in the next week.

2020-11-01 13:27 UTC, jmattheis requested changes

2020-11-01 13:27 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyServiceBinding.kt
> +open class GotifyServiceBinding : Activity() {
I rather not extend acitivty, this may restrict the user of the application. Can we have an interface like this?
```kotlin
data class Registration(val senderUid: Int, val url: String, val token: String)

interface GotifyBindingHandler {
    fun onConnected(service: GotifyServiceBinding) {
        service.doRegisterApp();
    }
    fun onRegistered(service: GotifyServiceBinding, registration: Registration)
    fun onUnRegistered(service: GotifyServiceBinding)
}

open class GotifyServiceBinding(var context: Context, var handler: GotifyBindingHandler) {
   ...
}
```

used like this:
```kotlin
class CheckActivity : Activity() {
    
    var binding = GotifyServiceBinding(this, object : GotifyBindingHandler {
        override fun onConnected(service: GotifyServiceBinding) {
            findViewById<TextView>(R.id.text_result_can_bind).apply {
                text = "connected"
            }
        }
        
        override fun onRegistered(service: GotifyServiceBinding) {
            findViewById<TextView>(R.id.text_result_register).apply {
                text = "true"
            }
            findViewById<TextView>(R.id.text_token_value).apply {
                text = TOKEN
            }
            findViewById<TextView>(R.id.text_url_value).apply {
                text = URL
            }
            val btn: Button = findViewById<View>(R.id.button_notify) as Button
            btn.isEnabled = true
        }
    })

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_check)

        /** If you want to use custom notification !
         * First of all, we set serviceName to our custom notif
         * service name to register it
         */
        //serviceName = "$packageName.services.CustomNotif"

        val btn: Button = findViewById<View>(R.id.button_notify) as Button
        btn.isEnabled = false

        binding.doBindService()
    }

    override fun onDestroy() {
        super.onDestroy()
        binding.doUnbindService();
    }

```

2020-11-01 13:27 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyServiceBinding.kt
> +    fun doUnbindService() {
remove the do from methods `unbindService` or `registerApp` should be enough.

2020-11-01 13:27 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyServiceNotification.kt
> +open class GotifyServiceNotification : Service() {
The user of the library should be responsible for providing the trustedId, then we don't have to do something with shared preferences.

2020-11-04 10:04 UTC, p1gp1g commented on build.gradle
> +apply plugin: 'com.android.library'
Should be fixed

2020-11-08 10:11 UTC, p1gp1g commented on src/main/java/com/github/gotify/connector/GotifyServiceNotification.kt
> +open class GotifyServiceNotification : Service() {
With the commit 2097b8be173a57435e683c011ef979049ac29e7a (notif service -> handler), the module gives a handler instead of a service to override.

I know there isn't a lot of added value compared to gotify next to another app, but there is also a default service, if someone wants to.

I didn't give the trustedId as a param of GotifyNotificationHandler because there isn't any context before the service is created, meaning that we can't load the trusted id from shared pref here. That's why we should override isTrused instead.

For convenience, GotifyBindingHandler registers the gotify ID in shared pref on registration and isTrusted from the GotifyServiceHandler checks in the shared pref. Both can be easily overridden.

2020-11-08 10:12 UTC, p1gp1g commented on src/main/java/com/github/gotify/connector/GotifyServiceBinding.kt
> +open class GotifyServiceBinding : Activity() {
Done
+ GotifyServiceBinding.register() now takes the service name as a parameter

2020-11-22 18:51 UTC, jmattheis requested changes
I think we are nearly there (:.

2020-11-22 18:51 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyServiceHandler.kt
> +    open fun onMessage(message: Message){}
onMessage should receive a Message in the gotify format, you can copy the message from gotify/android: 
https://github.com/gotify/android/blob/master/client/src/main/java/com/github/gotify/client/model/Message.java

2020-11-22 18:51 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/DefaultServiceNotification.kt
> +class DefaultServiceNotification : Service() {
I'd still prefer adding this only to the android connector template :x.

2020-11-22 18:51 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyServiceBinding.kt
> +            // There is nothing special we need to do if the service
Can we log these remote exceptions?

2020-11-22 18:51 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyServiceBinding.kt
> + * This Activity is used to register to gotify
This needs to be adjusted.

2020-11-22 18:51 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyServiceBinding.kt
> +    private var gService: Messenger? = null
Could you give these variables a better name, without g in it (as discussed in chat).

2020-11-22 18:51 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyServiceBinding.kt
> +        registerGotifyIdInSharedPref(service.context,registration.senderUid)
Can we move this also to the template app? The connector should only provide the minimum to make it work, how the trusteduid is provided should be configured in the user code. Yes, it is already possible to override this, but it also introduces unnecessary optional parameters on the com.github.gotify.connector.GotifyServiceHandler. I rather completely omit this from the library.

2020-11-22 18:51 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyServiceHandler.kt
> +open class GotifyServiceHandler(private val context: Context?) : Handler() {
This handler constructor is deprecated, GotifyServiceHandler should've the Looper as constructor param and forward it.
```
    /**
     * Default constructor associates this handler with the {@link Looper} for the
     * current thread.
     *
     * If this thread does not have a looper, this handler won't be able to receive messages
     * so an exception is thrown.
     *
     * @deprecated Implicitly choosing a Looper during Handler construction can lead to bugs
     *   where operations are silently lost (if the Handler is not expecting new tasks and quits),
     *   crashes (if a handler is sometimes created on a thread without a Looper active), or race
     *   conditions, where the thread a handler is associated with is not what the author
     *   anticipated. Instead, use an {@link java.util.concurrent.Executor} or specify the Looper
     *   explicitly, using {@link Looper#getMainLooper}, {link android.view.View#getHandler}, or
     *   similar. If the implicit thread local behavior is required for compatibility, use
     *   {@code new Handler(Looper.myLooper())} to make it clear to readers.
     *
     */
    @Deprecated
    public Handler() {
        this(null, false);
    }
```

2020-11-24 20:19 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyMessage.kt
> +    var extras: Map<String, Object>? = null
extras isn't filled by Bundle yet, maybe the message should be transmitted as json, to ease the transmission.

2020-11-29 14:50 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyMessage.kt
> +class GotifyMessage{
Is it possible to use a [data class](https://kotlinlang.org/docs/reference/data-classes.html) here?

2020-11-29 14:51 UTC, jmattheis commented on src/main/java/com/github/gotify/connector/GotifyServiceHandler.kt
> +open class GotifyServiceHandler() : Handler(Looper.getMainLooper()) {
Can you add the Looper as constructor argument to GotifyServiceHandler, the user of this library should choose the Looper.

2020-11-29 14:51 UTC, jmattheis reviewed
Okay, 2 things left, then I'll merge this.

2020-11-29 18:21 UTC, p1gp1g commented
I've corrected the 2 last things

2020-12-08 18:30 UTC, merged